import type { SlashCommand } from "./types"
import { INIT_TEMPLATE, REVIEW_TEMPLATE } from "./templates"

export const BUILTINS: SlashCommand[] = [
  { name: "clear", description: "Clear active chat messages", scope: "builtin", action: "clear" },
  { name: "btw", description: "Side chat: parallel/tool-free question that inherits context without cluttering the main thread. /btw <question>", scope: "builtin", action: "side-chat", needsArg: true },
  { name: "branch", description: "Fork this chat and switch to the fork; original stays intact. /branch [name]", scope: "builtin", action: "branch" },
  { name: "fork", description: "/branch alias. If forkSubagent is enabled: fork in background and bring the result here", scope: "builtin", action: "fork", needsArg: true },
  { name: "model", description: "Change model (open palette)", scope: "builtin", action: "model" },
  { name: "agent", description: "Chat with one specialist agent; you choose the preset persona", scope: "builtin", action: "agent", needsArg: true },
  { name: "workspace", description: "Choose workspace folder", scope: "builtin", action: "workspace" },
  { name: "search", description: "Search inside workspace", scope: "builtin", action: "search" },
  { name: "autopilot", description: "Open Autopilot", scope: "builtin", action: "routines" },
  { name: "orchestra", description: "Multi-agent mode: distribute model work to the worker pool in parallel (configure pool + switch mode)", scope: "builtin", action: "orchestra" },
  { name: "plugins", description: "Manage plugins (SettingsDrawer)", scope: "builtin", action: "plugins" },
  { name: "sdd", description: "Start SDD pipeline: requirement -> design -> prototype -> plan -> build", scope: "builtin", action: "sdd" },
  { name: "settings", description: "Open settings", scope: "builtin", action: "settings" },
  { name: "stop", description: "Stop the active stream", scope: "builtin", action: "stop" },
  {
    name: "init",
    description: "Create/update AGENTS.md (project instruction file)",
    scope: "builtin",
    template: INIT_TEMPLATE,
  },
  {
    name: "review",
    description: "Review changes [commit|branch|pr], default: uncommitted",
    scope: "builtin",
    template: REVIEW_TEMPLATE,
    subtask: true,
  },
  {
    name: "goal",
    description: "Persistent goal: model continues automatically until the goal is done (cancel with '/goal stop')",
    scope: "builtin",
    action: "goal",
    needsArg: true,
  },
  { name: "codemap-index", description: "Build Code Map index (Token Saving tool)", scope: "builtin", action: "codemap-index" },
  { name: "memory", description: "Manage memory files (view/edit)", scope: "builtin", action: "memory" },
  { name: "compact", description: "Compact context now: turn older messages into a memory summary (ignores threshold)", scope: "builtin", action: "compact" },
  { name: "rename", description: "Rename active chat: /rename <new title>", scope: "builtin", action: "rename", needsArg: true },
  { name: "resume", description: "Open chat list (search by name and continue)", scope: "builtin", action: "resume" },
  { name: "help", description: "Show all commands", scope: "builtin", action: "help" },
]
